# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='health',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Deffective', 'Deffective')], default='Functional', max_length=50, verbose_name='Health'),
        ),
    ]
