# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0006_remove_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_no',
            field=models.CharField(max_length=50, verbose_name='Serial No.'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emp_id',
            field=models.CharField(max_length=50, verbose_name='Emp ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=50, verbose_name='Emp ID'),
        ),
    ]
