# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0007_auto_20170216_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_inventory.Team'),
        ),
        migrations.AlterField(
            model_name='status',
            name='barcode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='mobile_inventory.Status'),
        ),
    ]
