# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0008_auto_20170217_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_inventory.Status'),
        ),
        migrations.AlterField(
            model_name='transactionborrow',
            name='borrower',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='mobile_inventory.User'),
        ),
    ]
