# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0011_auto_20170217_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='barcode',
            field=models.CharField(max_length=100, verbose_name='Barcode'),
        ),
    ]
