# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0012_auto_20170217_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='health',
            field=models.CharField(choices=[('Functional', 'Functional'), ('Defective', 'Defective')], default='Functional', max_length=50, verbose_name='Health'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
