# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0015_auto_20170222_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 22, 9, 35, 47, 944187, tzinfo=utc), verbose_name='Date'),
        ),
    ]
