# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0019_auto_20170222_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 2, 22, 17, 39, 27, 821899), verbose_name='Date'),
        ),
    ]
